# Generated by Django 4.1 on 2023-03-06 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="todo",
            name="status",
            field=models.CharField(
                choices=[
                    ("Backlog", "Backlog"),
                    ("In Progress", "In Progress"),
                    ("Finished", "Finished"),
                    ("Over Due", "Over Due"),
                    ("Trash", "Trash"),
                ],
                default="Backlog",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="todo",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
