# Generated by Django 4.1 on 2022-09-12 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
