# Generated by Django 4.1 on 2022-09-13 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0002_todo_is_deleted"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="todo",
            name="updated",
        ),
        migrations.AlterField(
            model_name="todo",
            name="status",
            field=models.CharField(
                choices=[
                    ("Backlog", "Backlog"),
                    ("In Progress", "In Progress"),
                    ("Finished", "Finished"),
                    ("Over due", "Over Due"),
                    ("Trash", "Trash"),
                ],
                default="Backlog",
                max_length=20,
            ),
        ),
    ]
