# Generated by Django 4.1 on 2022-09-13 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0003_remove_todo_updated_alter_todo_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
