# Generated by Django 4.1 on 2022-12-21 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0002_alter_todo_status_alter_todo_updated"),
        ("todo", "0004_todo_updated"),
    ]

    operations = []
